"""
cinematic_markdown.py — The TradeMan Chronicles Cinematic Output Writer

Writes haiku data to cinematic casefile markdown format:
  Assets/casefiles/casefile_001_main_a1b2c3d.md

Format:
  # CASE FILE — <title>
  *<subtitle>*
  
  Metadata (date, commit, branch, type, author)
  
  ### ACT I — THE SITUATION
  <when_where>
  
  ### ACT II — THE PLAYERS  
  <who_whom>
  
  ### ACT III — THE CONSEQUENCE
  <what_why>
  
  ---
  
  ### VERDICT
  <verdict>
  
  *Generated by The TradeMan Chronicles — Director's Cut*

Also writes episode markdown:
  Assets/episodes/episode_003.md

Usage:
    from cinematic_markdown import write_casefile, write_episode_markdown
    
    path = write_casefile(output_dir, commit, haiku, chronological_index)
    ep_path = write_episode_markdown(episode_dir, episode, haiku_list, episode_number)
"""

import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from git_commit_haiku import GIT_CRIME_LEXICON

# Default narrative roles if lexicon not available
_DEFAULT_LEXICON: Dict[str, str] = {
    "feat": "Rising action — He acquired a new weapon",
    "fix": "Damage control — The alibi was falling apart",
    "chore": "The grind montage — Three days. No sleep. Just code.",
    "refactor": "Identity crisis — He tore it all down and rebuilt himself",
    "docs": "The confession — He documented the crime in detail",
    "test": "Paranoia — He didn't trust himself. He built a lie detector.",
    "revert": "The flashback — He undid it. But you can't unring a bell.",
    "merge": "The conspiracy deepens — Two worlds collided. Nothing was the same.",
    "style": "Vanity — He polished the evidence",
    "ci": "The system closing in — Automated judgment approached",
    "build": "The forge — Infrastructure hammered into shape",
    "perf": "The chase — He made it faster to avoid himself",
    "hotfix": "2 AM damage control — Emergency. No witnesses.",
    "init": "The origin — The first sin. Before the evidence, there was the idea.",
    "wip": "The unfinished crime — Left at the scene, half-done",
}


def write_casefile(
    output_dir: Path,
    commit: Dict[str, str],
    haiku: Dict[str, str],
    chronological_index: int,
) -> Path:
    """Write a cinematic casefile markdown for a single haiku.
    
    Args:
        output_dir: Directory to write the casefile (e.g., Assets/casefiles/)
        commit: Commit metadata dict with keys: hash, type, msg, branch, author, date
        haiku: Haiku dict with keys: title, subtitle, when_where, who_whom, what_why, verdict
        chronological_index: 1-based position in repo history
        
    Returns:
        Path to the written markdown file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    
    short_hash = commit["hash"][:7]
    branch_safe = (commit.get("branch") or "main").replace("/", "-")
    
    # Filename: casefile_001_main_a1b2c3d.md
    filename = output_dir / f"casefile_{chronological_index:03d}_{branch_safe}_{short_hash}.md"
    
    # Get narrative role from lexicon
    commit_type = commit.get("type", "other")
    lexicon = GIT_CRIME_LEXICON if 'GIT_CRIME_LEXICON' in dir() else _DEFAULT_LEXICON
    narrative_role = lexicon.get(commit_type, f"Unknown crime — {commit_type}")
    
    # Extract fields from haiku with fallbacks
    title = haiku.get("title", f"CASE FILE — {short_hash}")
    subtitle = haiku.get("subtitle", "")
    when_where = haiku.get("when_where", "")
    who_whom = haiku.get("who_whom", "")
    what_why = haiku.get("what_why", "")
    verdict = haiku.get("verdict", "")
    
    # Build the markdown content
    content = f"""# {title}

*{subtitle}*

**Date:** {commit['date'][:10]}  
**Commit:** `{commit['msg']}`  
**Branch:** `{commit['branch']}`  
**Type:** `{commit_type.upper()}` — *{narrative_role}*  
**Author:** {commit['author']}

---

### ACT I — THE SITUATION

{when_where}

### ACT II — THE PLAYERS

{who_whom}

### ACT III — THE CONSEQUENCE

{what_why}

---

### VERDICT

{verdict}

*Generated by The TradeMan Chronicles — Director's Cut*
"""
    
    filename.write_text(content, encoding="utf-8")
    return filename


def write_episode_markdown(
    output_dir: Path,
    episode: Dict[str, Any],
    haiku_list: List[Dict[str, Any]],
    episode_number: int,
) -> Path:
    """Write an episode markdown file combining multiple casefiles.
    
    Args:
        output_dir: Directory to write the episode (e.g., Assets/episodes/)
        episode: Episode dict with keys: title, decade_summary, branch_note, max_ruling
        haiku_list: List of haiku dicts for casefile references
        episode_number: Episode number (1, 2, 3, ...)
        
    Returns:
        Path to the written markdown file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    
    filename = output_dir / f"episode_{episode_number:03d}.md"
    
    # Extract episode fields
    title = episode.get("title", f"EPISODE {episode_number}")
    decade_summary = episode.get("decade_summary", "")
    branch_note = episode.get("branch_note", "")
    max_ruling = episode.get("max_ruling", "")
    
    # Build casefile bullet list
    casefile_links = []
    for h in haiku_list:
        case_title = h.get("title", "Unknown Case")
        case_hash = h.get("commit_hash", h.get("hash", ""))[:7]
        casefile_links.append(f"  - {case_title} (`{case_hash}`)")
    
    casefiles_md = "\n".join(casefile_links)
    
    content = f"""# {title}

---

## THE DECADE IN BRIEF

{decade_summary}

---

## BRANCH REPORT

{branch_note}

---

## CASE FILES THIS EPISODE

{casefiles_md}

---

## MAX'S RULING

{max_ruling}

---

*Generated by The TradeMan Chronicles — Episode {episode_number}*
*{len(haiku_list)} case files compiled*
"""
    
    filename.write_text(content, encoding="utf-8")
    return filename


def write_season_manifest(
    output_dir: Path,
    episodes: List[Dict[str, Any]],
    season: int = 1,
) -> Path:
    """Write a season.json manifest for Remotion/keynote renders.
    
    Args:
        output_dir: Directory to write season.json
        episodes: List of episode dicts with full data
        season: Season number (default: 1)
        
    Returns:
        Path to the written JSON file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    
    manifest = {
        "season": season,
        "episode_count": len(episodes),
        "episodes": episodes,
    }
    
    filename = output_dir / f"season_{season}.json"
    filename.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    return filename


# ─── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse
    import sqlite3
    
    parser = argparse.ArgumentParser(description="Write cinematic markdown from DB")
    parser.add_argument("--casefile", action="store_true", help="Write all casefiles")
    parser.add_argument("--episode", type=int, help="Write specific episode")
    parser.add_argument("--all", action="store_true", help="Write all casefiles + episodes")
    parser.add_argument("--db", default="tmChron.db", help="Path to DB")
    args = parser.parse_args()
    
    from git_commit_haiku import get_db_connection, load_config
    
    cfg = load_config()
    db_path = cfg.get("db_path", args.db)
    casefile_dir = Path(cfg.get("casefile_dir", "Assets/casefiles"))
    episode_dir = Path(cfg.get("episode_dir", "Assets/episodes"))
    
    conn = get_db_connection(db_path)
    
    if args.casefile or args.all:
        print(f"Writing casefiles to {casefile_dir}...")
        rows = conn.execute("""
            SELECT * FROM haiku_commits 
            ORDER BY CASE WHEN chronological_index > 0 THEN chronological_index ELSE id END ASC
        """).fetchall()
        
        for row in rows:
            commit = {
                "hash": row["commit_hash"],
                "type": row["commit_type"],
                "msg": row["commit_msg"],
                "branch": row["branch"],
                "author": row["author"],
                "date": row["commit_date"],
            }
            haiku = {
                "title": row["title"],
                "subtitle": row["subtitle"],
                "when_where": row["when_where"],
                "who_whom": row["who_whom"],
                "what_why": row["what_why"],
                "verdict": row["verdict"],
            }
            path = write_casefile(casefile_dir, commit, haiku, row["chronological_index"])
            print(f"  ✓ {path.name}")
    
    if args.episode or args.all:
        # Get all episodes
        ep_rows = conn.execute("SELECT * FROM chronicle_episodes ORDER BY episode_number").fetchall()
        
        for ep_row in ep_rows:
            if args.episode and ep_row["episode_number"] != args.episode:
                continue
                
            # Load associated haikus
            commit_hashes = ep_row["commit_hashes"]
            if commit_hashes:
                import ast
                try:
                    hashes = ast.literal_eval(commit_hashes)
                except:
                    hashes = commit_hashes.split(",")
            else:
                hashes = []
            
            haikus = []
            for h in hashes:
                h = h.strip().strip("'\"")
                h_row = conn.execute(
                    "SELECT * FROM haiku_commits WHERE commit_hash LIKE ?",
                    (f"{h[:7]}%",),
                ).fetchone()
                if h_row:
                    haikus.append(dict(h_row))
            
            episode = {
                "title": ep_row["title"],
                "decade_summary": ep_row["decade_summary"],
                "branch_note": ep_row["branch_note"],
                "max_ruling": ep_row["max_ruling"],
            }
            
            path = write_episode_markdown(episode_dir, episode, haikus, ep_row["episode_number"])
            print(f"  ✓ {path.name}")
    
    conn.close()
    print("\nDone!")
